[project]
name = 'medicine-authenticity-checker'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.drug-registry]
path = 'contracts/drug-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.verification-gateway]
path = 'contracts/verification-gateway.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
